# Generated by Django 4.1.3 on 2023-02-22 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supermarket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pakhsh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, default=supermarket.models.set_persian_date, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('is_recieved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_done', models.BooleanField(blank=True, default=False, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pakhsh.product')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
