# Generated by Django 4.1.3 on 2023-02-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakhsh', '0002_product_image_alter_product_moq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
